# Generated by Django 4.0.4 on 2022-05-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.TextField(default=1652779416041, max_length=200),
            preserve_default=False,
        ),
    ]
